### ISSUE TITLE
感谢EFI,触摸板使用问题反馈

### ISSUE THREAD

**Issue by jimlgx** [twislyn/Hackintosh-ThinkPad-L490#1]
感谢提供L490 EFI,已经安装成功  macOs Catalina  10.15.3

使用您的 EFI 已经安装完成，基本可以作为工作使用
反馈一个问题：现在触摸板可以使用支持 单指移动鼠标，
          暂时不支持 双指上下滑动屏幕和窗口双指拖拽移动

  型号名称：	MacBook Pro
  型号标识符：	MacBookPro14,2
  处理器名称：	Quad-Core Intel Core i7
  处理器速度：	1.99 GHz
  处理器数目：	1
  核总数：	4
  L2缓存（每个核）：	256 KB
  L3缓存：	8 MB
  超线程技术：	已启用
  内存：	16 GB
  Boot ROM版本：	202.0.0.0.0
  Apple ROM信息：	Apple ROM Version.
  BIOS ID:MBP142.88Z.F000.B00.1909131802
  EFI Version:202.0.0.0.0
  Built by:     Clover

**Comment by twislyn** [comment]
触摸板暂无解决办法，不过你可以使用下最新的EFI，功能更全面
