### ISSUE TITLE
感谢制作这个efi

### ISSUE THREAD

**Issue by AlertConsole** [twislyn/Hackintosh-ThinkPad-L490#1]
我的是E490，10.15.1用2.1版本。目前没有发现问题。谢谢。找了很久之前的都是睡眠有问题。除了偶尔操作的时候会闪一下屏幕。

**Comment by ddy86** [comment]
能否告知一下怎么下载镜像的，微信公众号里面竟然没有打赏按钮

**Comment by twislyn** [comment]
There will be a full [EFI](https://github.com/sosiao/Hackintosh-ThinkPad-L490) for Monterey, you can watch it.

**Comment by twislyn** [comment]
> 能否告知一下怎么下载镜像的，微信公众号里面竟然没有打赏按钮

Find it in [here](https://blog.daliansky.net/).
