### ISSUE TITLE
使用v2.0版本安装10.15.4（19e2269） 显卡无法驱动

### ISSUE THREAD

**Issue by eric00liu** [twislyn/Hackintosh-ThinkPad-L490#2]
我的笔记本是thinkpad L490,使用v2.0版本安装10.15.4（19e2269）显存只有4M
请问应该如何解决这个问题

![image](https://user-images.githubusercontent.com/6258080/103098015-40929200-4644-11eb-9b0b-2adf26e6e804.png)

**Comment by 01super** [comment]
> 

老兄，还在搞这个电脑吗？可以传授一下经验吗

**Comment by farseenmanekhan1232** [comment]
add WhateverGreen kext , should help

**Comment by twislyn** [comment]
The version 2.0 is only for install. 
If you want graphics card works well, you need make it yourself. 
There will be a full [EFI](https://github.com/sosiao/Hackintosh-ThinkPad-L490) for Monterey, you can watch it.

**Comment by twislyn** [comment]
#

> 我的笔记本是thinkpad L490,使用v2.0版本安装10.15.4（19e2269）显存只有4M 请问应该如何解决这个问题
> 
> ![image](https://user-images.githubusercontent.com/6258080/103098015-40929200-4644-11eb-9b0b-2adf26e6e804.png)

You can use the latest version directly.
